export const tokens = [
  {
    name: "Brewlabs",
    symbol: "BREWLABS",
    isVerified: true,
    balance: 8282810.22,
    price: 0.044,
    value: 42422.22,
    isReward: true,
    isPriceUp: true,
    isScam: false,
    logo: "/images/dashboard/tokens/brewlabs.svg",
    reward: {
      totalRewards: 422.22,
      pendingRewards: 20.22,
      symbol: "BUSD",
    },
  },
  {
    name: "BNB",
    symbol: "BNB",
    isVerified: true,
    balance: 9282810.22,
    price: 0.044,
    value: 32442.22,
    isReward: false,
    isPriceUp: true,
    isScam: false,
    logo: "/images/dashboard/tokens/brewlabs.svg",
    reward: {
      totalRewards: 0,
      pendingRewards: 0,
      symbol: "",
    },
  },
  {
    name: "Sky Token",
    symbol: "TICKER",
    isVerified: false,
    balance: 8282810.22,
    price: 0.044,
    value: 32442.22,
    isReward: true,
    isPriceUp: false,
    isScam: false,
    logo: "/images/dashboard/tokens/brewlabs.svg",
    reward: {
      totalRewards: 2923,
      pendingRewards: 5,
      symbol: "SKY",
    },
  },
  {
    name: "I'm a scam token",
    symbol: "TICKER",
    isVerified: false,
    balance: 325612.22,
    price: 0.13,
    value: 4432.22,
    isReward: true,
    isPriceUp: false,
    isScam: true,
    logo: "/images/dashboard/tokens/brewlabs.svg",
    reward: {
      totalRewards: 1,
      pendingRewards: 532,
      symbol: "TICKER",
    },
  },
  {
    name: "Scam token",
    symbol: "TICKER",
    isVerified: false,
    balance: 325612.22,
    price: 0.13,
    value: 4432.22,
    isReward: true,
    isPriceUp: false,
    isScam: true,
    logo: "https://logos.covalenthq.com/tokens/0x90a1dd7f8dad69fd1000a2d185d29bfddce970f6.png",
    reward: {
      totalRewards: 1,
      pendingRewards: 532,
      symbol: "TICKER",
    },
  },
  {
    name: "Another Scam token",
    symbol: "TICKER",
    isVerified: false,
    balance: 325612.22,
    price: 0.13,
    value: 32.22,
    isReward: true,
    isPriceUp: false,
    isScam: true,
    logo: "/images/dashboard/tokens/brewlabs.svg",
    reward: {
      totalRewards: 1,
      pendingRewards: 56,
      symbol: "TICKER",
    },
  },
];
